version: "3.8"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    env_file:
      - 'env.influxdb'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=tig-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=123123123Aa
      - DOCKER_INFLUXDB_INIT_ORG=prjctr
      - DOCKER_INFLUXDB_INIT_BUCKET=ushkov
      - DOCKER_INFLUXDB_INIT_RETENTION=5d
    volumes:
      - ./srv/docker/influxdb/data:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    depends_on:
      - influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=prjctr
      - DOCKER_INFLUXDB_INIT_BUCKET=ushkov
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=UP9-ChsTzhRO95AHGZYfhrQaroksYdWPi7-S8J6l95qaev82DRR2LRQbl9rSYVhPZfbJpdOGCpZa-elVg1-3-Q==
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      - ./srv/docker/grafana/data:/var/lib/grafana

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./srv/docker/mongo/db:/data/db

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./srv/docker/es/db:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

  simple-page-app:
    build:
      context: ./simplepage/flaskapp/
      dockerfile: Dockerfile
    container_name: simple-page-app
    environment:
      MONGO_URL: mongodb://mongodb:27017/
    ports: 
      - 5000:5000
    restart: always
    depends_on:
      - mongodb
      - elasticsearch

